### PR TITLE
inject name in to plugin source

### PR DESCRIPTION
**Pull request by davetayls**

### CODE REVIEW

**Comment by vladikoff** [comment]
@davetayls @jzaefferer this PR is useful. However if the plugin author enters `my-plugin-name` it will break.
Thoughts?

**Comment by davetayls** [comment]
plugin names shouldn't really have hyphens in them as they wouldn't be valid JavaScript variables

**Comment by vladikoff** [comment]
Right now the init template would accept hyphens as the "Project Name"
Like so:

**Comment by shama** [comment]
Perhaps `js_safe_name` would be better. That should be available instead of `name` and is set here: https://github.com/gruntjs/grunt-init/blob/master/tasks/init.js#L100

**Comment by vladikoff** [comment]
@davetayls Care to update the PR with `js_safe_name` and squash the commits? :package:

**Comment by davetayls** [comment]
Sure I'll take a look.

**Comment by davetayls** [comment]
all sorted and squashed

**Comment by jzaefferer** [comment]
Looks good to me!

**Comment by shama** [comment]
Thanks @davetayls!

**Comment by davetayls** [comment]
@shama no probs :)

**Pull request merged**
